### ISSUE TITLE
Use semantic-release to remove burden on releaser(s)

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt-contrib-core#167]

**Comment by oliverfoster** [comment]
thanks @cahirodoherty-learningpool and @joe-allen-89 

stupendous job

**Comment by cahirodoherty-learningpool** [comment]
Cheers for getting those all added in @joe-allen-89, hopefully it makes your life easier 😂 
Very happy to have this in place. Saying that though, we should all keep an eye on merges/releases for a while and perhaps do spot checks to make sure all is well.

Also, it may be worthwhile for someone with Github admin permissions to change the default PR behaviour to be squash and merge for all the repos. I think it will help with notes on the tags and generally be cleaner git history on the plugins.
