### ISSUE TITLE
feature request: add _isStarted/.is-started to contentObjects (possibly articles & blocks too)

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-contrib-core#189]
I know we have `_isVisited` but that's quite limited in its usefulness as it:
 1. gets set to `true` if even you just go into the page but don't actually complete anything
 1. doesn't persist between sessions i.e. it's really just telling you 'the learner has been into this page in this session'

Example use-case: instead of having progress bars on the menu items I would prefer them to have a label displaying 'not started'/'started'/'completed' instead.

Similarly [this forum post](https://community.adaptlearning.org/mod/forum/discuss.php?d=3778) asks about the possibility of colouring 'incomplete' menu items differently.

**Comment by oliverfoster** [comment]
Having spent some time implementing `_isStarted`, I have concluded that the behaviour is practically identical to `_isVisited`, which now is retained over sessions. 
https://github.com/adaptlearning/adapt-contrib-core/blob/45b423a5387666307452a1698d1890820642a51e/js/models/adaptModel.js#L86-L102

`_isVisited` is set true on a model (and therefore a page) when any descendant is `_isComplete: true` or `_isInteractionComplete: true` or `_isVisited: true`. It does not take into account `_isOptional` nor `_requireCompletionOf`. `_isStarted` is, in theory, identical, it would be set to true when any descendant is `_isComplete: true` or `_isInteractionComplete: true` or `_isStarted: true`, perhaps with the caveat of only listening to the mandatory children.

Closing
