### ISSUE TITLE
API: Add global ESC keypress event

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt-contrib-core#191]
I'm mentioning this because it's a convention in web apps to use ESC to dismiss modal popups, items which have focus, etc. and I've noticed that various plugins are setting up listeners for the ESC key.

~~If accessibility mode is enabled ESC shouldn't trigger events.~~  

Something else mentioned for consideration is the possibility of introducing jquery keycombo into core.

**Comment by oliverfoster** [comment]
Closing as no need for over two years
