### ISSUE TITLE
feature request: ability to add text labels to buttons that are currently icon-only

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt-contrib-core#192]
For example, some of our clients require the notify popup close button to have a 'Close' label as well as the X icon. This can be done by overriding notify.hbs in the theme, but this isn't ideal - it would be nice to be able to set this properly via course.json

I'm thinking we could add this as a new feature for v5 (or v5.1), making use of the existing `_buttons` object in course.json - combined with a new `{{import_buttons}}` handlebars helper to allow that data to be made available to .hbs templates easily (it's currently only available to question components).

It's probably not sensible to try and get all of these done at once but for starters here's a list of the buttons that are currently icon-only and which might benefit from having the option to include a label:
* navbar back btn
* navbar home btn
* navbar drawer btn
* drawer back btn
* drawer close btn
* notify close btn
* hotgraphic popup close btn (listing separately purely because it has its own template)

**Comment by chris-steele** [comment]
Discussed with @guywillis. Time has marched on and we will soon have a [tooltip API](https://github.com/adaptlearning/adapt-contrib-core/pull/207). Given that translations can present layout difficulties with button labels, perhaps the tooltip is a better way to provide a textual cue. Direct labelling would be better left to project customisation if required.
