### ISSUE TITLE
Locking should not lock completed items

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-core#2]
For example: sequential locking requires the completion of the previous item. If the current item is already complete, it should not be locked.

This is particularly awkward if a user rests completion on a component in a previous topic. It then causes subsequent menu items to relock even when previously completed.

**Comment by danielghost** [comment]
I am not sure this fix should be applied as I can see issues where this could confuse users and conflict instructional text within a course. For example, a step locked course may have a message at the end informing a user that the course is now completed. If that last page has not yet been seen, but all other pages have been completed, resetting any page before the penultimate page won't prevent them from entering the last page and reaching the completed message, although at this point they won't actually be completed as they need to go back in to the earlier page that was reset. Previously they would have been forced to complete that earlier page again first, which may be a safer journey to avoid potential completion issues?

**Comment by oliverfoster** [comment]
`[IN]` = Incomplete
`[L]` = Locked
`[C]` = Complete

So in the use-case, we start with sequential locking or custom locking, where the second to last page is incomplete and the last page is locked:

```js
[ 0, 1, 2, 3, 4, 5, 6 ]
[ C, C, C, C, C, IN, L ] 
```

We then complete the second to last page, the last page becomes unlocked:

```js
[ 0, 1, 2, 3, 4, 5, 6 ]
[ C, C, C, C, C, C, IN ] 
```

Before we visit the last page, we go reset something in a completed page.

With this pr it would look like this:

```js
[ 0, 1, 2, 3, 4, 5, 6 ]
[ C, IN, C, C, C, C, IN ] 
// -- END --
```

As it is currenctly, it would go to:

```js
[ 0, 1, 2, 3, 4, 5, 6 ]
[ C, IN, L, L, L, L, L ] 
```
Such that all of the items are relocked and we lose access to all of your completed pages.
It requires us to complete the incomplete page in sequence before going back to:

```js
[ 0, 1, 2, 3, 4, 5, 6 ]
[ C, C, C, C, C, C, IN ] 
// -- END --
```

They both seem like pretty viable design choices. Testing seem to think the way it is currently is weirder than the proposal. 

We can't leave the pr here unfinished. So do I:

1. Continue with this pr
2. Provide a toggle for switching between the two locking styles
3. Have branching do a soft reset instead of a hard reset when resetting a branching article
