### ISSUE TITLE
Notify popup should allow disabling of subview

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt-contrib-core#208]
The notifyPopupView.addSubView should have a toggle to allow it to prevent appending.
This should possibly be global and component-level configurable

**Comment by oliverfoster** [comment]
Intriguing, what's the use-case?

**Comment by cahirodoherty-learningpool** [comment]
In this sample course
[course-title.zip](https://github.com/adaptlearning/adapt-contrib-core/files/9241288/course-title.zip)
you will see the question html becomes part of the feedback html. This will often not be desired. As well as that, the buttons are still actionable so I can layer up the feedback popups

**Comment by oliverfoster** [comment]
that's really odd, i wonder what changed to cause that.

**Comment by cahirodoherty-learningpool** [comment]
> that's really odd, i wonder what changed to cause that.

Yeah I tried to check the release diffs recently but can't see what has caused it

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-tutor/commit/f34b5fad26cb6d7272ec270d71ec5419dbaa6899#diff-583750802d6de6ec763daf6bc03d02ffbfa2528604b0798a94d81945cbb75780R22

**Comment by cahirodoherty-learningpool** [comment]
Thanks Oliver. I still don't really understand how the html was being rendered to be honest

**Comment by oliverfoster** [comment]
The notify title and tutor inline feedback title now require the `_id` to appropriately calculate the heading level, the `_id` had previously been used, when specified, to render the component view of the `_id` property. Just some overlapping bad behaviour.
