### ISSUE TITLE
Guard needed against empty child in adaptModel.getAllDescendantModels

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt-contrib-core#212]
### Subject of the issue/enhancement/features
We are seeing strange issues with large question banks that fall over when this._childrenCollection is returning arrays containing undefined

### Your environment
* FW5.22.0
* All browsers
* All devices

### Steps to reproduce
Difficult to say, but large assessments (40+ questions) that are using question banks. Somehow the this._childrenCollection is getting set to an array containing undefined. Difficult to debug exactly because of the sheer volume of loops over `setChildren()`

### Expected behaviour
Page should load as expected

### Actual behaviour
`adaptModel.js:471 Uncaught TypeError: Cannot read properties of undefined (reading 'hasManagedChildren') at adaptModel.js:471:18`

**Comment by cahirodoherty-learningpool** [comment]
It looks like this may have been caused by some missing Question Bank IDs/corrupted JSON. Typically the child _should_ be defined, but is it worth keeping this guard in to prevent failures from issues like this?

**Comment by oliverfoster** [comment]
I think it's worth warning in the assessment if banking IDs are missing and / or providing defaults. There's nothing worse than having a core bit of code which cleans up user errors without notification. I would say this guard should not be included as this failure is as expected and helpful for identifying other issues. It would have been much harder to debug without it.

**Comment by cahirodoherty-learningpool** [comment]
Closed in favour of https://github.com/adaptlearning/adapt-contrib-assessment/issues/173
