### ISSUE TITLE
Automated aria-levels in Adapt Authoring tool

### ISSUE THREAD

**Issue by StuartNicholls** [adaptlearning/adapt-contrib-core#240]
Currently, schemas across the adapt framework and plug-ins set the default value of the aria-level override (components/blocks etc) for the authoring tool to 0 (zero). This means that 0 is always applied to all components/block/article headings regardless of what the base values are set to in the conig.json

Concerns courses published in AAT only.

Suggest a null value or adding a check for 0 (or -1) or other falsy value. 

Additionally, the current Schema for config sets real numbers as strings, just highlighting this as it functions correctly both ways. See menu/page/notify.

`  
"_accessibility": {
    "_isEnabled": true,
    "_isSkipNavigationEnabled": true,
    "_ariaLevels": {
      "_menu": "1",
      "_menuGroup": "@menu+1",
      "_menuItem": "@menu+1",
      "_page": "1",
      "_article": "@page+1",
      "_block": "@article+1",
      "_component": "@block+1",
      "_componentItem": "@component+1",
      "_notify": "1"
    },`

**Comment by oliverfoster** [comment]
duplicate of #233 

pr https://github.com/adaptlearning/adapt-contrib-core/pull/234
