### ISSUE TITLE
Add aria-haspopup where necessary

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-core#245]
### Subject of the issue
[aria-haspopup](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-haspopup)
* Show feedback
* Hotgraphic

**Comment by joe-allen-89** [comment]
aria-haspopup has some issues with various screen readers and is not fully compatible (https://www.digitala11y.com/aria-haspopup-properties/). Looking through github threads, this has been an issue for years and has not been resolved, best to remove entirely.

Removed from components currently using - https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/259
