### ISSUE TITLE
Deprecation warnings should inform where the call is coming from

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt-contrib-core#249]
### Subject of the enhancement
Console warnings around deprecated calls are useful, but debugging their source can be a pain. I am proposing that we add a console.trace output to give a full call stack and thereby display the source of the deprecated call.

### Your environment
* FW5.22.5
* Chrome
* MacOS

### Steps to reproduce
Create a course that uses plugin(s) which have not yet been moved over to imported singletons (custom plugin or older version of one may be required)
Preview the course and inspect
DEPRECATED warnings will be displayed stating that old call type was made

### Expected behaviour
The source of this call should be listed

### Actual behaviour
The source of the call isn't currently listed

**Comment by oliverfoster** [comment]
You can look through the call stack that's printed with the warning.

**Comment by cahirodoherty-learningpool** [comment]
I'm an idiot. I'm not sure why it was in my head that we couldn't see that 🤦

**Comment by oliverfoster** [comment]
It's fine, don't worry.
