### ISSUE TITLE
`view:childAdded` of type trigger

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-core#259]
Often we only need to listen to `view:childAdded` events for specific type groups, so it may be worth considering triggering an additional [event](https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/views/adaptView.js#L211) with the model `_type` appended in the event name, so we don't have to return early from the generic event for views which may not be in scope?

**Comment by oliverfoster** [comment]
Sounds good
