### ISSUE TITLE
Control content max width via variable

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-core#260]
### Subject of the enhancement
Currently, the max width of content is generally hard-coded as @device-width-large. In less/core/page.less for instance, the page header's max width is set at @device-width-large:

```
.page {
  &__header-inner {
    .l-container-responsive(@device-width-large);
  }
}
```

It would be useful to have a dedicated variable for this like @content-max-width.  This could default to @device-width-large but could be easily overridden by the theme.

### Your environment
* AT 5.x

**Comment by chucklorenz** [comment]
@swashbuck Can you clarify? (there's such a history of device sizes and screen sizes being redundant and/or overwriting each other that it's hard for me to remember where we stand) 
Currently, I believe (pls correct me), defaults are set in [grunt](https://github.com/adaptlearning/adapt_framework/blob/4ddfb53c94628e7db16f494e8b2cb494f8febaf6/grunt/tasks/less.js#L20) but can be overwritten by [screenSizes added to config.json](https://github.com/adaptlearning/adapt_framework/blob/4ddfb53c94628e7db16f494e8b2cb494f8febaf6/grunt/tasks/less.js#L26-L28). The code then [passes these measurements](https://github.com/adaptlearning/adapt_framework/blob/4ddfb53c94628e7db16f494e8b2cb494f8febaf6/grunt/tasks/less.js#L47-L49) to src/core/less/_defaults/_variables.less where they finally [become Less variables](https://github.com/adaptlearning/adapt-contrib-core/blob/45b423a5387666307452a1698d1890820642a51e/less/_defaults/_variables.less#L23-L25) which can be consumed by stylesheets. 

[Vanilla repeats the same process](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/bb314efec4b6736a435efd2ecec50a8fd8b97d2c/less/_defaults/_spacing-containers.less#L3-L5) as _variables.less. I find this code to be ignored. I see no impact when this Vanilla code is replaced with specific rem measurements. However, I do find that changing the value of [Vanilla's @max-width](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/bb314efec4b6736a435efd2ecec50a8fd8b97d2c/less/_defaults/_spacing-containers.less#L7) does have an impact.

Screen sizes are currently configurable per course in config.json and in the AT's "Configuration settings". But I do not see where @max-width is exposed. And I don't see it listed in Vanilla's schema. Are you looking for @max-width to be configurable in config.json and exposed in the AT? 

(Hope I haven't confused a simple request.)

**Comment by swashbuck** [comment]
Hi, @chucklorenz.  I believe what you said is all correct, and thanks for the reminder of how the screen width variables are connected.

So, I am wanting to change the maximum widths of content containers via a new variable.  This would not affect the screen width breakpoints represented by @adapt-device-large or @device-width-large, for instance. This would simply decouple the max widths of content containers from these media query breakpoint variables.

For example, @device-width-large could still be set to 900px, which is the largest breakpoint in use.  However, through a new @content-max-width variable, we would be able to have a block or page header expand to a larger width like 1200px.  This is easy enough to do with custom Less, but having it as a variable would simplify things.

@content-max-width would not need to be configurable via config.json since it would not be used by JS when doing things around certain breakpoints (ex. loading different images for different screen widths).  However, it would be nice to include it and @max-width (if it's not already included) as configurable settings in the AT.

Also, just to clarify, @max-width controls the maximum width of the entire _page_, so this new variable would affect just the content containers (blocks, page headers, etc.).

Let me know if that makes sense.

**Comment by guywillis** [comment]
i agree that a separate variable `@content-width` makes sense as it decouples the content container width from a screen size break point value

I would suggest there be a few additions / changes:

* add new `@content-width` variable to core/less/_defaults/_variables.less
* update `.l-container-responsive(@device-width-large);` to `.l-container-responsive(@content-width);` article.less, block.less, notify.less, page.less in core/less/core

separately, in vanilla to allow for easier overriding within the theme

* add new `@content-width` variable to less/_defaults/_spacing-containers.less

**Comment by chucklorenz** [comment]
"@max-width" and "@content-width": I find these names a bit confusing on the face of them. 
"@max-width" doesn't say what it is the max-width of. 
And "@content-width" sounds like it governs the widths of all content whereas Brad sounded like he wanted to use this variable to override widths of certain structural blocks.

@swashbuck Is your intent for this new variable to be employed across the board as @guywillis seems to be suggesting or for it to be used in certain circumstances as an override? 

I understand that we should be hesitant to change the names of variables already in use, but ought we consider changing 
 "@max-width" to "@max-page-width"?

Will the new variable (@content-width/@content-max-width) require a default?

**Comment by guywillis** [comment]
I agree that the variables names could be made more descriptive. 

* `@max-width` becomes `@max-page-width` in core and vanilla - this could be either as a breaking change or by a bit of variable nesting
* new variable `@content-container-width` in core and vanilla

As Brad has mentioned above, the `@content-container-width` variable would have the value `@device-width-large` by default within core and vanilla to retain the current sizing

**Comment by swashbuck** [comment]
> @swashbuck Is your intent for this new variable to be employed across the board as @guywillis seems to be suggesting or for it to be used in certain circumstances as an override?

Correct, this would be a global variable as @guywillis has described.

If we changed `@max-width` to `@max-page-width`, would it make sense for the new content container variable to be `@max-content-width`?  That way, they both contain 'max' to indicate they're used for max-width values.

**Comment by guywillis** [comment]
Further instances of `.l-container-responsive(@device-width-large);` appears in the following files:

* languagePicker.less - adapt-contrib-languagepicker
* boxMenu.less - adapt-contrib-boxMenu
* boxMenuGroup.less - adapt-contrib-boxMenu

**Comment by guywillis** [comment]
task list

- [ ] create new `@max-content-width` variable, set to inherit value of `@device-width-large` to ensure backwards compatibility
- [ ] create new `@max-page-width` variable, set to inherit value of `@max-width` to ensure backwards compatibility
- [ ] apply above to vanilla

update `.l-container-responsive(@device-width-large)` to `.l-container-responsive(@max-content-width)`
- [ ] update core 
  - [ ] article.less
  - [ ] block.less
  - [ ] notify.less
  - [ ] page.less
- [ ] update languagePicker
- [ ] update boxmenu 
- [ ] update boxmenuGroup

update `.l-container-responsive(@max-width);` to `.l-container-responsive(@max-page-width);`
- [ ] update boxmenu

update `@max-width` to `@max-page-width`
- [ ] update vanilla
  - [ ] columns.less
  - [ ] theme-extras.less
