### ISSUE TITLE
score value responsibility

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-core#262]
Currently [tracking.js](https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/tracking.js#L49) is responsible for determining what score values to submit, but I think this should probably be the responsibility of the relevant tracking plugins instead.

The `isPercentageBased` property of an assessment shouldn't really be used to determine the score format submitted, as I would argue this is more for internal calculations within assessments and their results. Depending on the configuration, using this value can lead to SCORM errors as the property now becomes tied to the SCORM version. For example, SCORM 1.2 courses where the assessment raw score value exceeds 100, will always need `isPercentageBased: true`, and will error if not. SCORM 2004 courses which can separate raw and scaled scores, would need `isPercentageBased: false`.

If `OfflineStorage` always just sends the actual raw value regardless, leaving the tracking plugins to convert these values into the relevant format, any potential configuration errors are removed and `isPercentageBased` becomes decoupled and only serves the assessment logic.

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/scorm/wrapper.js#L227 would need to convert the raw score into a percentage. Likewise, other tracking plugins may need to change certain logic.

**Comment by chris-steele** [comment]
Agreed, perhaps trigger `tracking:submitScore` as is done for completion and let tracking plugins determine what to do.

**Comment by danielghost** [comment]
Resolved by https://github.com/adaptlearning/adapt-contrib-core/pull/316.
