### ISSUE TITLE
Drawer opens on left side of screen on first interaction

### ISSUE THREAD

**Issue by cahirodoherty-learningpool** [adaptlearning/adapt-contrib-core#312]
### Subject of the issue/enhancement/features
Possibly caused by https://github.com/adaptlearning/adapt-contrib-core/issues/272

When the drawer icon is first clicked on the course the drawer is aligned to the left of the page instead of the right as expected. Interacting with the glossary when aligned to the left then forces the drawer to the right side of the screen as expected.
Also if you close the drawer and access it again in the same session then it will always appear aligned to the right.

### Your environment
* Framework v5.26.1
* Vanilla v9.4.3
* Box Menu v6.3.5

### Steps to reproduce
Create a new course
Add a page with a text component on it
Add any of the extensions that appear in the drawer - resources, glossary, etc
Ensure there are items added to the extension
Preview the course
Click on the drawer icon from either the menu or within the first page

### Expected behaviour
Drawer will open on the right side of the screen

### Actual behaviour
Drawer opens on the left of the screen when first accessed, but will then appear on the right for any subsequent access

**Comment by guywillis** [comment]
Further to the above, it appears as though this bug occurs when multiple plugins are loaded into the drawer and the user is presented the choice between them.

If a singular plugin is added to drawer the position of the drawer is correct.

**Comment by danielghost** [comment]
This shouldn't be released as the ability to set the drawer position for individual views has been lost, regardless of whether it was launched from the drawer menu or directly from another plugin.

If launched via the drawer menu, consideration needs to be made regarding whether the position for a custom view shoudl be allowed to be different to that of the menu view position. Also need to account for the use of the back button when returning back to the menu view, should the positions be different.
