### ISSUE TITLE
Fresh install generating questionModel error

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt-contrib-core#323]
### Subject of the issue/enhancement/features
I'm receiving syntax errors while compiling within questionModel.js. Going to supply a PR.

### Your environment
* version 5.28.3
* All browsers
* All devices

### Screenshots (if you can)
![image](https://user-images.githubusercontent.com/7740674/224414976-3366e83d-a14d-4509-bccc-f4bb4d06aa80.png)

**Comment by cahirodoherty-learningpool** [comment]
That was caused by my carelessness. Apologies!

**Comment by oliverfoster** [comment]
don't worry, we got it, thanks for releasing so speadily
