### ISSUE TITLE
_shouldSubmitScore missing from config.model.schema

### ISSUE THREAD

**Issue by k-jensen** [adaptlearning/adapt-contrib-core#340]
### Subject of the issue/enhancement/features
Score not being sent to LMS.

There was a recent change to the Scoring API https://github.com/adaptlearning/adapt-contrib-core/pull/316 
Where the score is sent based on config._shouldSubmitScore settting.
It's not possible to set this in the Authoring Tool (v0.10.5), as it's missing from the config.model.schema

So it defaults to all courses not submitting the score.

### Your environment
* version (AT/Framework) **v5.28.7**
* which browser and its version **any**
* device(s) + operating system(s) **any**

### Steps to reproduce
Create a course in the Authoring Tool using the extensions:
- Spoor
- Assessment
Launch the course in a LMS, complete course, view score. (Tested on ScormCloud)

### Expected behaviour
When completing the course, the status and score is sent to the LMS

### Actual behaviour
Status is logged, score is not

**Comment by danielghost** [comment]
Not related to #316, but missing since the move from [spoor](https://github.com/adaptlearning/adapt-contrib-spoor/commit/c140fa49e2cd77baf524181f6ace8492e24bf45d) - https://github.com/adaptlearning/adapt-contrib-core/commit/513afd13eda52c19e80f1b18c179cb18458400f5.
