### ISSUE TITLE
Improve Breakpoints - Mismatch between js and css

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-core#371]
### Subject of the issue
Ref: https://github.com/adaptlearning/adapt-contrib-core/issues/362

We have four ranges and three names, that are out of alignment:

| Name | Value | Range | JS | CSS |
|----|----|--------|----|-----|
| n/a | n/a | 0 - 519 | small | small |
| small | 520 | 520 - 759 | medium | small |
| medium | 760 | 760 - 899 | large | medium |
| large | 900 | 900+ | large | large |

Breakpoints:
https://github.com/adaptlearning/adapt-contrib-core/blob/c7bb3c0ce2b78c57f5d6e67cccb443642736f18f/js/models/configModel.js#L11-L13

In the css, medium starts, equal to the medium value:
https://github.com/adaptlearning/adapt-contrib-core/blob/c7bb3c0ce2b78c57f5d6e67cccb443642736f18f/less/core/component.less#L15-L29
> The min- and max- queries are inclusive of the specified values, for example min-width: 400px tests for a width of 400px or greater. 
Ref: https://developer.chrome.com/blog/media-query-range-syntax/

In the js, medium starts equal or above small:
https://github.com/adaptlearning/adapt-contrib-core/blob/c7bb3c0ce2b78c57f5d6e67cccb443642736f18f/js/device.js#L82-L88

#### adapt-contrib-core:
* [Image switching](https://github.com/adaptlearning/adapt-contrib-core/blob/c7bb3c0ce2b78c57f5d6e67cccb443642736f18f/templates/image.jsx#L14) for accordion, gmcq, all jsx components that use that helper...
* [Instruction text](https://github.com/adaptlearning/adapt-contrib-core/blob/c7bb3c0ce2b78c57f5d6e67cccb443642736f18f/templates/header.jsx#L37) for all jsx components...

#### adapt-contrib-hotgraphic
* [Switch to narrative](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/0448e67af46b451e4ad71ae1ddec7a5cd198960a/js/hotgraphicView.js#L30)

#### adapt-contrib-narrative
* [Switch to hotgraphic](https://github.com/adaptlearning/adapt-contrib-narrative/blob/68d59fba24366b236f24c3c2e1b1e28b23648f9d/js/NarrativeView.js#L78)

#### adapt-contrib-boxMenu
* [Image switching](https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/df22de08aee5ab3395de44fd4a1e9491bd0be888/js/BoxMenuView.js#L73)

#### adapt-contrib-vanilla
* [Image switching](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/js/themePageView.js#L46)

#### adapt-contrib-code
* [Notify title padding](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/less/core/notify.less#L30)
* [Notify image alignment](https://github.com/adaptlearning/adapt-contrib-core/blob/c7bb3c0ce2b78c57f5d6e67cccb443642736f18f/less/core/notify.less#L39)
* [Tooltip max width](https://github.com/adaptlearning/adapt-contrib-core/blob/c7bb3c0ce2b78c57f5d6e67cccb443642736f18f/less/core/tooltip.less#L79)
* [Navigation label show](https://github.com/adaptlearning/adapt-contrib-core/blob/c7bb3c0ce2b78c57f5d6e67cccb443642736f18f/less/core/nav.less#L133)
* [Component wrapping](https://github.com/adaptlearning/adapt-contrib-core/blob/c7bb3c0ce2b78c57f5d6e67cccb443642736f18f/less/core/component.less#L10)

#### adapt-contrib-boxMenu
* [Item wrapping](https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/df22de08aee5ab3395de44fd4a1e9491bd0be888/less/boxMenuItem.less#L8)

#### adapt-contrib-accordion
* [Image margin, alignment and visibility](https://github.com/adaptlearning/adapt-contrib-accordion/blob/58a2777b4e4cd4b4b68ed6a5388047fb39243e36/less/accordion.less#L35)

#### adapt-contrib-hotgraphic
* [Popup image margin, alignment and visibility](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/0448e67af46b451e4ad71ae1ddec7a5cd198960a/less/hotgraphicPopup.less#L42)

#### adapt-contrib-narrative
* [Image alignment, etc](https://github.com/adaptlearning/adapt-contrib-narrative/blob/68d59fba24366b236f24c3c2e1b1e28b23648f9d/less/narrative.less#L14)

#### adapt-contrib-vanilla
* [Quotes](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/less/core/global.less#L37)
* [Media icons](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/less/plugins/adapt-contrib-media/mep.less#L39)
* [Blocks reverse](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/less/project/theme-blocks.less#L10)
* [Columns](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/less/project/columns.less#L2)
* [Title sizes](https://github.com/adaptlearning/adapt-contrib-vanilla/blob/d5a2a5f34f74585fe39723178328d830a76f90e1/less/_defaults/_font-mixins.less#L72)

**Comment by oliverfoster** [comment]
### Solution 1:

| Range | JS | CSS |
|--------|----|-----|
| 0 - 519 | xsmall | xsmall |
| 520 - 759 | small | small |
| 760 - 899 | medium | medium |
| 900+ | large | large |

Change the javascript to match the css, adding `xsmall` in the process:
```js
  if (screenSizeEmWidth >= largeEmBreakpoint) {
    screenSize = 'large';
  } else if (screenSizeEmWidth >= mediumEmBreakpoint) {
    screenSize = 'medium';
  } else if (screenSizeEmWidth >= smallEmBreakpoint) {
   screenSize = 'small';
  } else {
    screenSize = 'xsmall';
  }
```

Impact assessment:
* Most images will switch from small to large at 900 instead of at 760
* Background images will switch from small to medium at 760 instead of 520 and from medium to large at 900 instead of 760
* `mobileInstruction` will stay until 900 instead of 760
* hotgraphic and narrative will switch at 900 instead of 760

**Comment by swashbuck** [comment]
> hotgraphic and narrative will switch at 900 instead of 760

Once these changes are made, we should take a look at these 2 plugins and see if `medium` would be a better breakpoint to use.

**Comment by oliverfoster** [comment]
The shift to align the js and css was fixed in https://github.com/adaptlearning/adapt-contrib-core/pull/363
PR for adding `xsmall` to the schemas https://github.com/adaptlearning/adapt-contrib-core/pull/372
