### ISSUE TITLE
"_isDefaultNavigationDisabled": true throws error

### ISSUE THREAD

**Issue by chucklorenz** [adaptlearning/adapt-contrib-core#419]
### Subject of the issue
After setting `"_isDefaultNavigationDisabled": true`, the page fails to load and error is reported in the console.

### My environment
* FW v5.31.17; core v6.38.6
* Chrome desktop

### Steps to reproduce
1. Add the following to course.json:
```JSON
"_navigation": {
    "_isDefaultNavigationDisabled": true
}
```
2. Run course

### Expected behaviour
The page should load without the navigation bar.

### Actual behaviour
The page fails to load.
Error present in console:
![image](https://github.com/adaptlearning/adapt-contrib-core/assets/9489014/8adc32df-3bc0-4b1c-8a64-dd4b925e31ee)

**Comment by joe-allen-89** [comment]
@chucklorenz I'm able to replicate this, from what I can see this issue is coming from the PLP, do you have PLP enabled with _isDefaultNavigationDisabled set to true?

**Comment by joe-allen-89** [comment]
@chucklorenz You anticipated correctly, thanks for getting back to me, I'll close this issue as it has been added and PR raised on PLP - https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/193
