### ISSUE TITLE
Expand COMPLETION_STATE enums

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-core#424]
Expand https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/enums/completionStateEnum.js to account for the different values as per https://github.com/adaptlearning/adapt-contrib-spoor/pull/280#discussion_r1279112556?

Do we want all the values in here though as you could argue that some are specific to SCORM? Outside of spoor, no other hardcoded instances occur within the framework. https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/tracking.js only uses the currently available enums.

Which additional values would we want:
- [x] "completed"
- [x] "passed"
- [x] "failed"
- [x] "incomplete"
- [ ] "browsed"
- [x] "not attempted"
- [ ] "not_attempted" (mentioned in SCORM 2004 spec - mapped to "not attempted")
- [ ] "unknown"

**Comment by danielghost** [comment]
Closing as the enums will be added directly to spoor plugin instead for this use case.

**Comment by danielghost** [comment]
'NOT ATTEMPTED' enum to be added as this will be referenced outside the spoor plugin for OfflineStorage objectives.

**Comment by oliverfoster** [comment]
All looks good to me
