### ISSUE TITLE
Tooltips duplicating on Firefox

### ISSUE THREAD

**Issue by joe-allen-89** [adaptlearning/adapt-contrib-core#429]
### Subject of the issue/enhancement/features
When hovering over a nav item in Firefox a new tooltip is constantly added to the dom until you move your cursor away from the button. 

### Your environment
* v5.31.21 - core 6.39.0
* Firefox

### Steps to reproduce
Set up a course with tooltips on nav items, open in Firefox and hover over a nav button

### Expected behaviour
One tooltip is shown

### Actual behaviour
Repeatedly adds an additional tooltip to the dom.

**Comment by swashbuck** [comment]
I can reproduce this:
![duplicate-labels](https://github.com/adaptlearning/adapt-contrib-core/assets/898168/69d76400-a0cf-464b-b497-b1d0530cfbb3)
