### ISSUE TITLE
`itemsQuestionModel._isAtLeastOneCorrectSelection` not a boolean

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-core#454]
Since https://github.com/adaptlearning/adapt-contrib-core/commit/f9de89394ad418c9b7fdefbbd12b9659a090f827, `_isAtLeastOneCorrectSelection` returns a number rather than a boolean - https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/models/itemsQuestionModel.js#L95. This doesn't actually cause an issue, as any value > 0 will return true when used conditionally, but technically this isn't the expected value.

**Comment by oliverfoster** [comment]
It's an oversight. It should be wrapped in a `Boolean()` cohersion.
