### ISSUE TITLE
SCORM Interaction Latency - is this implemented?

### ISSUE THREAD

**Issue by paulstevendev** [adaptlearning/adapt-contrib-core#456]
When looking at the interaction data being recorded by a SCORM 1.2 Adapt course I am not seeing any value for latency.

Upon investigating I can see the following code in questionView.js in the latest code for adapt-contrib-core

` getLatency() {
    return null;
  }`

Can I just confirm this would imply this is not supported?

Thanks

Paul

**Comment by oliverfoster** [comment]
Yup. Not implemented.
