### ISSUE TITLE
Last tooltip displayed remains until next tooltip is displayed

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt-contrib-core#461]
### Subject of the issue
When navigating through a course with a screen reader, the last tooltip displayed remains on screen until the next element with a tooltip is displayed.

### Your environment
* FW v5.33.1 / Core v6.41.2
* Safari running Mac voiceOver

I don't have access to another screen reader to test if this is specific to voiceOver.

### Steps to reproduce
Navigate through the course (using `control` + `option` and arrow keys with voiceOver). Notice, any buttons with tooltips enabled, the tooltip will remain on screen until the next button with tooltips enabled is in focus, and the tooltip updated. See screenshots and comments below.

The last navigation button (with tooltip enabled) remains on screen even though focus has moved on to the page title.
<img width="1259" alt="nav_focus" src="https://github.com/adaptlearning/adapt-contrib-core/assets/7045330/432681b9-c99d-4001-b95c-995978e5aa17">

The navigation tooltip remains on screen until the next button (with tooltip enabled) has focus.
<img width="1253" alt="pagenav_focus_1" src="https://github.com/adaptlearning/adapt-contrib-core/assets/7045330/ece63039-6c77-4df2-8c2b-a2c969d31616">

When focus returns to an element without a tooltip, the last tooltip displayed remains again.
<img width="1252" alt="pagenav_focus_2" src="https://github.com/adaptlearning/adapt-contrib-core/assets/7045330/e03b6e27-3d40-4314-bc09-dda8300687f4">

**Comment by oliverfoster** [comment]
This is as expected. The browser is unaware of the screen reader cursor. Tooltips show when browser focused.

**Comment by kirsty-hames** [comment]
Thanks for confirming @oliverfoster  - I'll close the ticket.
