### ISSUE TITLE
Tooltip API - Allow delay to be configurable

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-core#482]
### Subject of the enhancement
When using the Tooltip API, there is a slight delay when hovering over an element before the tooltip appears. This delay is hardcoded [here](https://github.com/adaptlearning/adapt-contrib-core/blob/6657b362f59cccbb71e49b0e306227fd7c25ddce/js/views/TooltipView.js#L30).

```
this.onMouseOver = _.debounce(this.onMouseOver, 500);
```

It would be ideal if we could configure what this delay is. For example, in _course.json_, add a new property for the delay:

```
"_tooltips": {
  "_isEnabled": true,
  "_delay": 500
}
```

**Comment by oliverfoster** [comment]
Why? It's setup like this to allow a linger or next with the screen reader tab key to either show the tooltip or not. Tooltips read out loud when they are shown.

**Comment by swashbuck** [comment]
There may be a use case where the preference is that the tooltip is shown instantly or near instantly. Being able to set this to 0 or 100 would help with this.

**Comment by oliverfoster** [comment]
What's the use-case? Client push back?

**Comment by swashbuck** [comment]
> What's the use-case? Client push back?

Sort of. Predicting potential client push back with an implementation on a navigation button. Client hasn't seen it yet.

**Comment by swashbuck** [comment]
I think we can close this. It turns out the issue I was having was related to a performance issue with tooltips, and that issue has been resolved. It was causing a long delay before the tooltip appeared.
