### ISSUE TITLE
Setting language of course for Google Translate

### ISSUE THREAD

**Issue by johanlavenius** [adaptlearning/adapt-contrib-core#499]
### Subject of the issue/enhancement/features
index_lms.html contains <html id="adapt" class="no-js" lang="en" dir="ltr"> and is not reflecting the language of the course and Chrome translates the course with "wrong words" when certain settings is used.

### Your environment
- Framework 5.31.10
- Chrome (all versions)
- Windows 10

### Steps to reproduce
Create a course in Swedish. Use for example the Swedish word "Hat" (Meaning hate).
In Chrome (chrome://settings/languages) activate Google Translate. Set Translate to Swedish. Add English to the list of languages that should be translated automatically.

### Expected behaviour
The example swedish word "Hat" should still show up as the swedish word "Hat".

### Actual behaviour
The swedish word "Hat" is translated to "Hatt" (Its also a swedish word meaning hat. The thing you wear on your head).

This translation can be difficult to find in a long course. Most of the words seems just fine.

### Suggestion
The lang-attribute should reflect the language setting of the course or a separate setting in adapt-contrib-spoor.

**Comment by oliverfoster** [comment]
Please try the two pull requests attached.

**Comment by johanlavenius** [comment]
Works perfectly
