### ISSUE TITLE
Missing titles for feedback Notify popups

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-core#535]
### Subject of the issue
I believe this is a bug, but let me know if it is intended behavior.

If `_feedback.altTitle` is not present, is an empty value, or is the same value as `_feedback.title`, the title is not shown in the popup. However, if `_feedback.altTitle` is different from `_feedback.title` (either different text or just a single space character), then the title appears as expected.

You can test this with the core course from running `adapt create course` and viewing the Question Components topic.

This may be caused by #509 .

### Your environment
* FW 5.38.2
* Core 6.46.7

### Steps to reproduce
Configure the `_feedback` object in one of the following ways:

1. `_feedback.title` is the same as `_feedback.altTitle`
2. `_feedback.altTitle` is removed completely
3. `_feedback.altTitle` is an empty string ""

For example:

```
"_feedback": {
  "title": "Feedback",
  "altTitle": "Feedback",
  "correct": "Correct feedback text.",
  "_incorrect": {
    "notFinal": "",
    "final": "Incorrect feedback text."
  }
},
```

### Expected behaviour
"Feedback" title should appear.

<img src="https://github.com/adaptlearning/adapt-contrib-core/assets/898168/86088319-21b5-4067-ae65-b2ec78ae7099" width="350">

### Actual behaviour
No title appears

<img src="https://github.com/adaptlearning/adapt-contrib-core/assets/898168/486f7b03-e326-4cf0-80fc-ec75e90a1a55" width="350">

**Comment by oliverfoster** [comment]
Have you read https://github.com/adaptlearning/adapt-contrib-core/pull/510 ? Does it cover your bug?

**Comment by swashbuck** [comment]
> Have you read #510 ? Does it cover your bug?

@oliverfoster I've read through that ticket, but it's a bit confusing. There's also the [comment](https://github.com/adaptlearning/adapt-contrib-core/pull/510#issuecomment-2020156721) from @kirsty-hames that was left unresolved, from what I can tell.

If `_feedback.altTitle` is meant to be for screenreaders, why is the `_feedback.title` visibility dependent on it (see "Steps to reproduce" above)? It just seems unintuitive to me. And if the developer wants to intentionally hide the Notify title, this seems like a weird way to go about it.

**Comment by oliverfoster** [comment]
Is the supposition that `altTitle` should be change the way `title` is read but that `title` should still remain visible when supplied?
I had thought that `altTitle` were only to be used when no `title` was defined.

It's probably either/or because the notify `role=dialog` has an `aria-labelledby` requirement that must be configured with the id of a readable area. A visible title would read secondarily to the `altTitle` but not as the notify dialog label.

> There's also the https://github.com/adaptlearning/adapt-contrib-core/pull/510#issuecomment-2020156721 from @kirsty-hames that was left unresolved, from what I can tell.

Cahir implicitly resolved it with a subsequent pr I think. I was positive that there was a further comment from him, but I can't see it now.

**Comment by swashbuck** [comment]
> Is the supposition that `altTitle` should change the way `title` is read but that `title` should still remain visible when supplied? I had thought that `altTitle` were only to be used when no `title` was defined.

@oliverfoster I believe so, yeah. For instance, why is the title hidden completely if `altTitle` is absent or empty but there is still a value for `title`? Shouldn't it show the `title` value rather than hiding it? I can see this causing confusion in the AAT if course creators remove the `altTitle` value.

**Comment by oliverfoster** [comment]
Weird.

https://github.com/adaptlearning/adapt-contrib-core/blob/6a0014b60a2d3f5ea20f867ff06f4bc936bac094/js/models/questionModel.js#L286

It seems that `altTitle` defaults to [`_globals._accessibility.altFeedbackTitle`](https://github.com/adaptlearning/adapt-contrib-core/blob/6a0014b60a2d3f5ea20f867ff06f4bc936bac094/schema/course.model.schema#L360-L368) when no `_feedback.altTitle` is present.

https://github.com/adaptlearning/adapt-contrib-core/blob/6a0014b60a2d3f5ea20f867ff06f4bc936bac094/js/models/questionModel.js#L287

And that `title` can only be `altTitle` when no `_feedback.title` nor `component.title` is set.

https://github.com/adaptlearning/adapt-contrib-core/blob/6a0014b60a2d3f5ea20f867ff06f4bc936bac094/js/models/questionModel.js#L290

Then going forward `altTitle` is used for `isAltTitle`, so there must have been no `_feedback.title` nor `component.title` for this to be true.

It then goes almost straight through tutor and and notify view

https://github.com/adaptlearning/adapt-contrib-core/blob/6a0014b60a2d3f5ea20f867ff06f4bc936bac094/templates/notifyPopup.hbs#L16-L20

Is it that when `_feedback.altTitle` is empty it equals [`_globals._accessibility.altFeedbackTitle`](https://github.com/adaptlearning/adapt-contrib-core/blob/6a0014b60a2d3f5ea20f867ff06f4bc936bac094/schema/course.model.schema#L360-L368) which set to `"Feedback"`, which makes `altTitle` `"Feedback"` and that then equals `_feedback.title` which is also `"Feedback"` in your example?

**Comment by swashbuck** [comment]
> Is it that when _feedback.altTitle is empty it equals [_globals._accessibility.altFeedbackTitle](https://github.com/adaptlearning/adapt-contrib-core/blob/6a0014b60a2d3f5ea20f867ff06f4bc936bac094/schema/course.model.schema#L360-L368) which set to "Feedback", which makes altTitle "Feedback" and that then equals _feedback.title which is also "Feedback" in your example?

@oliverfoster Yes, that seems to be the explanation for all 3 cases under "Steps to reproduce" above. The only way that the title _will_ appear is if `altTitle` is set to something other than `title`. It can even be a space character like `" "` since that would technically be different from `title`.

**Comment by oliverfoster** [comment]
We could probably solve it by the `isAltTitle` derivation to the following:
```js
const isAltTitle = altTitle && !feedback.title && !this.get('title');
```
Where it's only true when there is no feedback title or component tile.

**Comment by swashbuck** [comment]
> We could go one step further and force it to be true if _feedback.altTitle is explicitly set? That would make that property very clear. It depends if we think altTitle should take precedence of title when set or if altTitle should only be used when title isn't set.

I think I prefer this option. So, a developer / course creator would only set a value for `altTitle` if we do _not_ want to show a title in the Notify. If we do this, I'd suggest removing any `altTitle` values from the [sample course](https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/components.json) since it is currently confusing.

Curious what others think, especially those involved with some of these recent changes. @kirsty-hames @cahirodoherty-learningpool @joe-allen-89 @joe-replin

**Comment by kirsty-hames** [comment]
> > We could go one step further and force it to be true if _feedback.altTitle is explicitly set? That would make that property very clear. It depends if we think altTitle should take precedence of title when set or if altTitle should only be used when title isn't set.

I think `altTitle` should only be used when a `title` isn't set. I think on screen and accessible text should be consistent. So yes to forcing `isAltTitle` to be true if `_feedback.altTitle` is explicitly set.

> I think I prefer this option. So, a developer / course creator would only set a value for `altTitle` if we do _not_ want to show a title in the Notify. If we do this, I'd suggest removing any `altTitle` values from the [sample course](https://github.com/adaptlearning/adapt_framework/blob/master/src/course/en/components.json) since it is currently confusing.

I'd agree. Yes to removing any `altTitle` values from the sample course.

**Comment by oliverfoster** [comment]
No, it would not make sense. There should be no cases where altTitle should be used as an accessible alternative to the title unless there is no title.

**Comment by kirsty-hames** [comment]
> * If `_feedback.title` is set, a title is displayed with this value
> * If `_feedback.title` is _not_ set, it falls back to the component title/displayTitle and that is displayed
> * If `_feedback.altTitle` is set, it is used as an aria label

This makes sense to me. With the following amend to the last point.

If `_feedback.altTitle` is set, it is used as an aria label and no visual title is displayed.

**Comment by oliverfoster** [comment]
@swashbuck are you fixing?

**Comment by swashbuck** [comment]
It would also be useful to update the feedback titles section in the Question Model wiki while we're at it.

https://github.com/adaptlearning/adapt_framework/wiki/Question-model#feedback-titles
