### ISSUE TITLE
Update deprecated warning for drawer.triggerCustomView

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-core#542]
I believe this deprecated warning should be for `drawer.removeDrawer`? Otherwise, the notice doesn't make sense.
https://github.com/adaptlearning/adapt-contrib-core/blob/6a0014b60a2d3f5ea20f867ff06f4bc936bac094/js/deprecated.js#L50-L53

I don't know if `drawer.removeDrawer` was actually the previous name of the function. I'm inferring this from the `drawer.closeDrawer` deprecated message:
https://github.com/adaptlearning/adapt-contrib-core/blob/6a0014b60a2d3f5ea20f867ff06f4bc936bac094/js/deprecated.js#L54-L57

Suggest changing to:
```
 'drawer:removeDrawer'() { 
   logging.deprecated('Use drawer.remove, Adapt.trigger(\'drawer:removeDrawer\') will be removed in the future'); 
   drawer.remove(); 
 }, 
```

**Comment by oliverfoster** [comment]
That deprecated warning is where we used to use events to trigger drawer behaviour rather than functions.
Pr: https://github.com/adaptlearning/adapt-contrib-core/commit/0a0f3aa2690521085c79831b3902a7548f21049e

**Comment by oliverfoster** [comment]
Would  you mind correcting the description for the triggerCustomView error please?
