### ISSUE TITLE
Custom Locking when using grouped items is broken

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-core#546]
### Subject of the issue
Content objects are not being appropriately locked when using [custom locking](https://github.com/adaptlearning/adapt_framework/wiki/Locking-objects-with-'_isLocked'-and-'_lockType'#custom) with grouped items.

### Your environment
* FW 5.38.2
* Core 6.48.0
* Box Menu 6.7.0

### Steps to reproduce
1. In _course.json_, set the lock type to "custom":

```
"_lockType": "custom",
```

2. In _contentObjects.json_, add content objects to groups using the [example](https://github.com/adaptlearning/adapt-contrib-boxMenu/blob/1fc32a36cfc04bf654db16cf4c8b280ba7d9734d/example.json#L62) in Box Menu. For example, content objects should use a custom lock type like:

```
"_lockedBy": ["co-200"]
```

3. Leave the last content object **ungrouped**.

### Expected behaviour
On the menu, content objects that are locked by a preceding content object should appear as locked and should not be accessible.

### Actual behaviour
Only the last content object appears locked since it is ungrouped.

### Related issues
https://github.com/adaptlearning/adapt-contrib-core/issues/124

### Screenshots
<img src="https://github.com/adaptlearning/adapt-contrib-core/assets/898168/7511f535-28d5-45d0-8be8-a3765aae197e" width="450">

**Comment by oliverfoster** [comment]
Did you try https://github.com/adaptlearning/adapt-contrib-core/pull/125#issuecomment-1161887230

**Comment by oliverfoster** [comment]
> @oliverfoster Ah, yep. That was the problem. I needed to add `"_lockType": "custom"` to every content object that should be locked. With grouped items, I was thinking you just needed `"_lockType": "custom"` in course.json, and then `_lockedBy` for each content object.

The _lockType custom is specific to its ower only. Some of the other types do configure child locking, but custom does not.
