### ISSUE TITLE
Assessment not submitting score properly

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt-contrib-core#55]
Should the default “adapt create course” install submit a score on assessment completion to the LMS? This is v5.18.1 with the latest plugins and config._spoor._shouldSubmitScore = true.

I’m getting no score sent to SCORM cloud with this setup.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-spoor/commit/f3315d658b7c6f09b88bb9ad760cb6e5eb86728e
https://github.com/adaptlearning/adapt-contrib-core/pull/30

Prs moved the behaviour but not the `_shouldSubmitScore` property.

**Comment by deltanetdan** [comment]
Tracking still needs _requireAssessmentCompleted = true on [this line ](https://github.com/adaptlearning/adapt-contrib-core/blob/master/js/tracking.js#L21)before it will send the score.

A user might want to setup the course to track course completion only and still send the score to the LMS.
