### ISSUE TITLE
Component titles are not being read out by screenreaders on IOs Devices

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt-contrib-core#69]
**Steps to replicate**
1. Create a course with a text component
2. Navigate to the text component title using a screen reader on an iOS device (Im using an iPhone 7)

**Expected Results**
The screenreader should read out the the component titles

**Actual Results**
The component titles are not being read out

**Additional Notes**
I am on framework 15.8.4

**Comment by oliverfoster** [comment]
I'll try and give this a test this week, it seems odd that they're not working correctly. It's tested quite thoroughly.

Which device and ios version?

**Comment by eleanor-heath** [comment]
@oliverfoster I tested on my iPhone 7 iOS 15.3.1. The issue was raised by the client for iPad/ioS v15.x/Safari/Voiceover screen reader.

**Comment by oliverfoster** [comment]
Can't replicate:
https://user-images.githubusercontent.com/7974663/157737494-ade6a134-0283-4f53-b822-6f0c2a96c681.mp4

**Comment by oliverfoster** [comment]
closed all tested fine
